### ISSUE TITLE
Renommer le dépôt covid19-algorithme-orientation-elixir ?

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid-19-orientation-elixir#2]
Hello, pour anticiper d'autres dépôts avec d'autres codes sources, je propose de renommer celui-ci en `covid19-algorithme-orientation-elixir` - comme ça l'info sur le langage est dans le seul suffixe. WDYT?

**Comment by bonjourmauko** [comment]
Oui ! Il faut que de ton côté tu mettes à jour le submodule.
