### ISSUE TITLE
Extraire le code pour les specs openapi ?

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid-19-orientation-elixir#3]
Est-ce qu'on ne ferait pas un dépôt `covid19-algorithme-orientation-openapi` juste pour les specifications Open API ?

Je pense que ce serait plus lisible.

**Comment by bonjourmauko** [comment]
Ce n'est pas une mauvaise idée, la seule chose que je me demande est comment les générer ... laisse-moi réfléchir un sec.

Avec un submodule git ?

**Comment by bonjourmauko** [comment]
Sinon publier à la main à chaque version bump.

**Comment by bonjourmauko** [comment]
Done already !
