### ISSUE TITLE
Renommer le dépot covid19-algorithme-orientation-api

### ISSUE THREAD

**Issue by bzg** [Delegation-numerique-en-sante/covid-19-orientation-elixir#37]
Le nom actuel donne l'impression que c'est un exemple d'implémentation de l'algorithme en Elixir, alors que c'est tout une API.

Ce sera plus simple pour s'y retrouver si on nomme ce dépôt `covid19-algorithme-orientation-api`, non?

Eventuellement, le code de calcul de l'algorithme peut être extrait pour être poussé en exemple sur [le dépôt de documentation](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation)?

**Comment by bonjourmauko** [comment]
Done !
